import { useState } from 'react';
import Head from "next/head";
import { DM_Sans } from "next/font/google";
import { Menu, SquareChevronDown } from "lucide-react";
import styles from "@/styles/Home1.module.css";

import image1 from '../../public/image1.jpeg';
import DateToCare from '../../public/DataToCare.png';

const dmSans = DM_Sans({ subsets: ["latin"] });

// const animate = (variants: any) => {
//   return {
//     initial: "initial",
//     animate: "animate",
//     exit: "exit",
//     variants
//   }
// }

// const perspective = {
//   initial: {
//     // y: 0,
//     scale: 1,
//     opacity: 1
//   },
//   enter: {
//     // y: 0,
//     scale: 1,
//     opacity: 1
//   },
//   exit: {
//     // y: -100,
//     scale: 0.3,
//     opacity: 0.5,
//     transition: {
//       duration: 1.2,
//       ease: [0.76, 0, 0.24, 1]
//     }
//   }
// }

// const slideUp = {

// }

export default function Home() {
  const [open, setOpen] = useState(false);

  const handleMenu = () => setOpen(true);
  const handleCloseMenu = () => {
    if (open) {
      setOpen(false);
    }
  }

  return (
    <>
      <Head>
        <title>Akinwale Habib</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={`${styles.gridContainer} ${dmSans.className}`} onClick={handleCloseMenu}>
        <header className={styles.header}>
          <p>
            <a href="#">Ak.h</a>
          </p>

          <button
            className={`${styles.menu}`}
            onClick={handleMenu}
          >
            <Menu />
          </button>

          {
            open && (
              <div className={styles.mobileNavContainer}>

                <nav className={styles.mobileNav}> 
                  <ul>
                    <li><a href="#projectssection">Projects</a></li>
                    <li><a href="#">Resume</a></li>
                    <li><a href="#">Courses</a></li>
                    <li><a href="#">Contact</a></li>
                  </ul>
                </nav>
              </div>
            )
          }

          <div className={styles.navContainer}>
            <nav className={styles.nav}> 
              <ul>
                <li><a href="#projectssection">Projects</a></li>
                <li><a href="#">Resume</a></li>
                <li><a href="#">Courses</a></li>
                <li><a href="#">Contact</a></li>
              </ul>
            </nav>
          </div>
        </header>

        <div
          className={`${styles.image}`}
          onClick={handleCloseMenu}
          style={{
            backgroundImage: `url(${image1.src})`,
            backgroundSize: 'cover'
          }}></div>

        <p className={`${styles.firstName}`}>Habib</p>
        <p className={`${styles.middleName}`}>Folorunsho</p>
        <p className={`${styles.lastName}`}>Akinwale</p>

        <p className={`${styles.introduction}`} onClick={handleCloseMenu}>
          I'm a <span><strong>Senior Software Engineer</strong> with experience in backend, web, and hybrid native applications. I have a foundation in ITIL, and i also possess technical project management skills.</span> Previously at <a href="https://www.savics.org" target="_blank">Savics</a>, <a href="https://www.andela.com" target="_blank">Andela</a>, and the <a href="https://www.aun.edu.ng" target="_blank">American University of Nigeria.</a>
        </p>

        <div className={`${styles.more}`}><SquareChevronDown /></div>
      </section>

      <section id='projectssection'>
        <header>
          <h3 className={`${styles.projectsHeader} ${dmSans.className}`}>Projects</h3>
        </header>

        <div className={`${styles.projects} ${dmSans.className}`}>

          <div className={`${styles.project} ${styles.long}`}>
              <img
                src={DateToCare.src}
                alt="DataToCare product icon"
                className={styles.projectImage} />
              <p className={styles.description}>
                DataToCare is a fully customizable suite of integrated applications that connects national laboratory networks by collecting diagnostic and patient data at the facility level, displaying real-time information on a dashboard to facilitate decision-making at the central level, and notifying test results to medical teams and patients.
              </p>
              <a className={styles.action} href="https://datatocare.org">Visit</a>
          </div>

          <div className={styles.project}>
              <h3 className={styles.title}>Elderly care platform</h3>
              <p className={styles.description}>
                On-demand care provider for the elderly members of society.
              </p>
              <a className={styles.action} href="#">Visit</a>
          </div>

          <div className={styles.project}>
              <h3 className={styles.title}>CV Maker</h3>
              <p className={styles.description}>
                Resume and cover letter generator for professionals.
              </p>
              <a className={styles.action} href="#">Visit</a>
          </div>

          <div className={`${styles.project}`}>
              <h3 className={styles.title}>Crash Courses</h3>
              <p className={styles.description}>
                Succinct software development and engineering tutorials.
              </p>
              <a className={styles.action} href="https://crashcours.es" target='_blank'>Visit</a>
          </div>
          
          <div className={`${styles.project} ${styles.wide}`}>
              <h3 className={styles.title}>ThriftBox</h3>
              <p className={styles.description}>
                Core banking application service for cooperative societies and credit unions.
              </p>
              <a className={styles.action} href="#">Visit</a>
          </div>

          <div className={`${styles.project}`}>
              <h3 className={styles.title}>Fund Pool</h3>
              <p className={styles.description}>
                Group shopping app for individuals.
              </p>
              <a className={styles.action} href="#">Visit</a>
          </div>
        </div>
      </section>
    </>
  );
}
