import { useState } from 'react';
import Head from "next/head";
import { DM_Sans } from "next/font/google";
import { Menu } from "lucide-react";
// import { motion } from "framer-motion";

// import styles from "@/styles/Home.module.css";
import styles from "@/styles/Home1.module.css";
import image1 from '../../public/image1.jpeg';

const dmSans = DM_Sans({ subsets: ["latin"] });

// const animate = (variants: any) => {
//   return {
//     initial: "initial",
//     animate: "animate",
//     exit: "exit",
//     variants
//   }
// }

// const perspective = {
//   initial: {
//     // y: 0,
//     scale: 1,
//     opacity: 1
//   },
//   enter: {
//     // y: 0,
//     scale: 1,
//     opacity: 1
//   },
//   exit: {
//     // y: -100,
//     scale: 0.3,
//     opacity: 0.5,
//     transition: {
//       duration: 1.2,
//       ease: [0.76, 0, 0.24, 1]
//     }
//   }
// }

// const slideUp = {

// }

export default function Home() {
  const [open, setOpen] = useState(false);

  const handleMenu = () => setOpen(true);
  const handleCloseMenu = () => setOpen(false);

  return (
    <>
      <Head>
        <title>Akinwale Habib</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      { /* <motion.div
          initial={{ y: -5 }}
          animate={{
            y: [ null, -5, -50, -5, -30, -5 ],
            transition: {
              ease: "easeOut",
              duration: 2,
              repeat: Infinity,
              repeatDelay: 2
            }
          }}
          className={styles.moreContainer}
        >
            <MoveDown size={32} absoluteStrokeWidth />
        </motion.div> */ }

      <section className={`${styles.gridContainer} ${dmSans.className}`}>
        <header className={styles.header}>
          <p>
            <a href="#">Ak.h</a>
          </p>
          <div>
            <button
              className={`${styles.menu}`}
              onClick={handleMenu}
            >
              <Menu />
            </button>
            <nav className={styles.nav}> {/* style={{ display: open ? 'block' : 'none' }} */}
              <ul>
                <li><a href="#">Projects</a></li>
                <li><a href="#">Resume</a></li>
                <li><a href="#">Courses</a></li>
                <li><a href="#">Contact</a></li>
              </ul>
            </nav>
          </div>
        </header>

        {/* <main className={styles.main} onClick={handleCloseMenu} onDragEnd={handleCloseMenu}> */}
          <div
            className={`${styles.image}`}
            style={{
              backgroundImage: `url(${image1.src})`,
              backgroundSize: 'cover'
            }}></div>

          <p className={`${styles.firstName}`}>Habib</p>
          <p className={`${styles.middleName}`}>Folorunsho</p>
          <p className={`${styles.lastName}`}>Akinwale</p>

          <p className={`${styles.introduction}`}>
            I'm a <span><strong>Senior Software Engineer</strong> with experience in backend, web, and hybrid native applications. I have a foundation in ITIL, and i also possess technical project management skills.</span> Previously at <a href="https://www.savics.org" target="_blank">Savics</a>, <a href="https://www.andela.com" target="_blank">Andela</a>, and the <a href="https://www.aun.edu.ng" target="_blank">American University of Nigeria.</a>
          </p>

          <div className={`${styles.more}`}>More</div>
        {/* </main> */}
      </section>

      <section className="projects"></section>
    </>
  );
}
